source_files = \
	core/src/processing/core/PApplet.java \
	core/src/processing/core/PConstants.java \
	core/src/processing/core/PFont.java \
	core/src/processing/core/PGraphics.java \
	core/src/processing/core/PGraphicsAndroid2D.java \
	core/src/processing/core/PImage.java \
	core/src/processing/core/PMatrix.java \
	core/src/processing/core/PMatrix2D.java \
	core/src/processing/core/PMatrix3D.java \
	core/src/processing/core/PShape.java \
	core/src/processing/core/PShapeOBJ.java \
	core/src/processing/core/PShapeSVG.java \
	core/src/processing/core/PStyle.java \
	core/src/processing/core/PVector.java \
	core/src/processing/data/FloatDict.java \
	core/src/processing/data/FloatList.java \
	core/src/processing/data/IntDict.java \
	core/src/processing/data/IntList.java \
	core/src/processing/data/JSONArray.java \
	core/src/processing/data/JSONObject.java \
	core/src/processing/data/JSONTokener.java \
	core/src/processing/data/Sort.java \
	core/src/processing/data/StringDict.java \
	core/src/processing/data/StringList.java \
	core/src/processing/data/Table.java \
	core/src/processing/data/TableRow.java \
	core/src/processing/data/XML.java \
	core/src/processing/event/Event.java \
	core/src/processing/event/KeyEvent.java \
	core/src/processing/event/MouseEvent.java \
	core/src/processing/event/TouchEvent.java \
	core/src/processing/opengl/FontTexture.java \
	core/src/processing/opengl/FrameBuffer.java \
	core/src/processing/opengl/LinePath.java \
	core/src/processing/opengl/LineStroker.java \
	core/src/processing/opengl/PGL.java \
	core/src/processing/opengl/PGLES.java \
	core/src/processing/opengl/PGraphics2D.java \
	core/src/processing/opengl/PGraphics3D.java \
	core/src/processing/opengl/PGraphicsOpenGL.java \
	core/src/processing/opengl/PShader.java \
	core/src/processing/opengl/PShapeOpenGL.java \
	core/src/processing/opengl/tess/ActiveRegion.java \
	core/src/processing/opengl/tess/CachedVertex.java \
	core/src/processing/opengl/tess/Dict.java \
	core/src/processing/opengl/tess/DictNode.java \
	core/src/processing/opengl/tess/Geom.java \
	core/src/processing/opengl/tess/GLUface.java \
	core/src/processing/opengl/tess/GLUhalfEdge.java \
	core/src/processing/opengl/tess/GLUmesh.java \
	core/src/processing/opengl/tess/GLUtessellatorImpl.java \
	core/src/processing/opengl/tess/GLUvertex.java \
	core/src/processing/opengl/tess/Mesh.java \
	core/src/processing/opengl/tess/Normal.java \
	core/src/processing/opengl/tess/PGLU.java \
	core/src/processing/opengl/tess/PGLUtessellator.java \
	core/src/processing/opengl/tess/PGLUtessellatorCallback.java \
	core/src/processing/opengl/tess/PGLUtessellatorCallbackAdapter.java \
	core/src/processing/opengl/tess/PriorityQ.java \
	core/src/processing/opengl/tess/PriorityQHeap.java \
	core/src/processing/opengl/tess/PriorityQSort.java \
	core/src/processing/opengl/tess/Render.java \
	core/src/processing/opengl/tess/Sweep.java \
	core/src/processing/opengl/tess/TessMono.java \
	core/src/processing/opengl/tess/TessState.java \
	core/src/processing/opengl/Texture.java \
	src/processing/mode/android/AndroidBuild.java \
	src/processing/mode/android/AndroidEditor.java \
	src/processing/mode/android/AndroidKeyStore.java \
	src/processing/mode/android/AndroidMode.java \
	src/processing/mode/android/AndroidPreprocessor.java \
	src/processing/mode/android/AndroidRunner.java \
	src/processing/mode/android/AndroidSDK.java \
	src/processing/mode/android/AndroidToolbar.java \
	src/processing/mode/android/AVD.java \
	src/processing/mode/android/BadSDKException.java \
	src/processing/mode/android/Commander.java \
	src/processing/mode/android/Device.java \
	src/processing/mode/android/DeviceListener.java \
	src/processing/mode/android/Devices.java \
	src/processing/mode/android/EmulatorController.java \
	src/processing/mode/android/Export.java \
	src/processing/mode/android/JarSigner.java \
	src/processing/mode/android/Keys.java \
	src/processing/mode/android/KeyStoreManager.java \
	src/processing/mode/android/LogEntry.java \
	src/processing/mode/android/Manifest.java \
	src/processing/mode/android/Permissions.java \
	src/processing/mode/android/SDKDownloader.java \
